### ISSUE TITLE
Error while matching patterens

### ISSUE THREAD

**Issue by MuhammadUsman-coder** [xnl-h4ck3r/urless#1]
Hi , 
I just downloaded it and ran it on  100 urls and it ran fine .
Than i tried to ran it on a large file containing URLs and it is giving below error:
'ERROR matchesPatterns 1: missing ), unterminated subpattern at position 410'
Screenshot is attached
![error](https://user-images.githubusercontent.com/54319802/186399911-6b912132-88ea-4d82-8d09-adb302bf629c.png)

**Comment by xnl-h4ck3r** [comment]
Hi @MuhammadUsman-coder 
Thanks for taking the time to raise an issue for this. I'm not able to reproduce the problem. I sthere any way you could send me the file you are testing with so I can track down the problem? If you don't want to attach here, you could send it to me on dicord perhaps (user xnl-h4ck3r#1197)?
Kind regards
Xnl

**Comment by xnl-h4ck3r** [comment]
Hi @MuhammadUsman-coder, can you give me any more information about the input file you used when you got these errors as I'd really like to resolve the problem for you. Thanks

**Comment by MuhammadUsman-coder** [comment]
Hi @xnl-h4ck3r , sorry for the late response .
I cannot share the file. It was a 1 GB text file with 28 lac entries .
I wrote a regex to do the job and it worked fine. 

Thanks 
Kind regards
Usman

**Comment by gprime31** [comment]
Same problem, it happens when the source file has garbage in it or special chars, it doesn't ignore them like uro does.

**Comment by gprime31** [comment]
![2022-09-03_23-45](https://user-images.githubusercontent.com/44535257/188296410-f0c4c14d-9e3f-43d9-910f-6c9a1180fa73.png)
kinda slow also.

**Comment by xnl-h4ck3r** [comment]
> Same problem, it happens when the source file has garbage in it or special chars, it doesn't ignore them like uro does.

Hi @gprime31. Can you give me an example of some lines in the input file that cause this issue? I'm having problems reproducing it myself. Thanks!

**Comment by gprime31** [comment]
@xnl-h4ck3r  sent it  to you on Discord.

**Comment by xnl-h4ck3r** [comment]
Thanks @gprime31 
I've fixed this issue now if you want to get the latest version. I wasn't escaping a string before searching with regex. It mainly occurred if there was a bracket in the URL. 
I'll look into the speed as a separate problem.
Thanks
