### ISSUE TITLE
add differential response content filtering

### ISSUE THREAD

**Issue by JaveleyQAQ** [xnl-h4ck3r/urless#10]
Implement differential response content filtering; use case: Numerous URLs retrieved from Waymore might have been removed. Despite the server issuing a 200 status code, an error page has been universally configured. While discrepancies can often be identified by the content-length, minor variations still exist. It is essential to save each response content and compare the differences in responses each time for similarity. If the similarity exceeds 95%, the pages are considered identical, and only one instance should be preserved.

**Comment by xnl-h4ck3r** [comment]
Hi @JaveleyQAQ. Thanks for taking the time to raise an issue. Urless is just a passive tool to reduce a list of the URLs. It currently doesn't make any requests to be able to look at responses. The initial list of URLs can potentially be huge, and I don't think I'd want to make a change to this tool to make so many requests as there is a lot of considerations with that. Thanks for the suggestion, but I think urless is best left at the passive task it was designed for. Maybe that could be an idea for a separate active tool.
