### ISSUE TITLE
There is a problem with the script filtering regular matches

### ISSUE THREAD

**Issue by 419066074** [xnl-h4ck3r/urless#3]
Hi author, there is a problem with this script, when there‘s’ a URL in the asset similar to http://1.1.1.1:8080/tmp, the script will delete (:80) by default and after filtering the asset it will become http://1.1.1.180/tmp

**Comment by xnl-h4ck3r** [comment]
Hi @419066074. Thanks for taking the time to raise that. I'll get that sorted soon!

**Comment by xnl-h4ck3r** [comment]
Hi @419066074. This should be fixed in v0.5 now. Let me know if it has sorted to the problem for you. Many thanks
