### ISSUE TITLE
could you make -c for config directory!

### ISSUE THREAD

**Issue by blackcodersec** [xnl-h4ck3r/urless#9]
could you make -c for config directory!

**Comment by blackcodersec** [comment]
![image](https://github.com/xnl-h4ck3r/urless/assets/72689232/a42daf9e-5074-4f6f-9d9c-77804e7f94f2)


how can I filter this type of garbage urls?

**Comment by xnl-h4ck3r** [comment]
> ![image](https://private-user-images.githubusercontent.com/72689232/321213304-a42daf9e-5074-4f6f-9d9c-77804e7f94f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MzQ2NjQsIm5iZiI6MTcxMjgzNDM2NCwicGF0aCI6Ii83MjY4OTIzMi8zMjEyMTMzMDQtYTQyZGFmOWUtNTA3NC00ZjZmLTlkOWMtNzc4MDRlN2Y5NGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDExMTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlMjhkYWFkYzBkYTJkYmExZjYxNzc0OGI5OTcyYTMwMDRmN2JiNzdjNGYzYzM0YmUzNmFhZDI0ZTY2MjdlODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nQxWsUJ_29mczULXadT-wPsAKxsgjn7izXVEjoKihaE)
> 
> how can I filter this type of garbage urls?

I haven't got chance to look at this properly yet, but I will get to it and give you a proper reply soon

**Comment by blackcodersec** [comment]
ok thanks

**Comment by xnl-h4ck3r** [comment]
> ![image](https://private-user-images.githubusercontent.com/72689232/321213304-a42daf9e-5074-4f6f-9d9c-77804e7f94f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NjQ2ODcsIm5iZiI6MTcxMjg2NDM4NywicGF0aCI6Ii83MjY4OTIzMi8zMjEyMTMzMDQtYTQyZGFmOWUtNTA3NC00ZjZmLTlkOWMtNzc4MDRlN2Y5NGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE5Mzk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NWYyYzhmODg5YjYwYWJjYWQwOWU1MGVlNTc4YWU4ODc0YWViM2Y4ODVkMDAxZDBmYmJkY2UyZTIwYmJjMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vGaSKof2Edz675WGq-bufrbGP0WRUXzbgRz9dPCxlLA)
> 
> how can I filter this type of garbage urls?

From the information I can see, all those urls that look similar apart from a differeing parameter value should have been condensed to one line. Is that screenshot from the output of `urless`?

**Comment by blackcodersec** [comment]
yes that output is from `urless` and check this new screenshot I filter `.js` extension, but I think not working `-fe`.

![image](https://github.com/xnl-h4ck3r/urless/assets/72689232/64b9d8d2-d928-4c29-b9b4-6d3a5522ceef)

**Comment by xnl-h4ck3r** [comment]
Hi @blackcodersec. From the screenshot you posted, it looks like you've started the `-fe` value with a double quote, and then tried closing with a single quote. The next double quote is at the end of the `-fk` value. So actually the `-fe` values doesn't have `.js`, it has `.js' -fk 'bog` as a value. If you use `-v` option you can double check the values you are using. Can you correct the quotes and let me know if you still have a problem? Thanks

**Comment by blackcodersec** [comment]
ohh sorry sorry, I didn't see I close with a single quote.
Now ok, its working fine.

**Comment by xnl-h4ck3r** [comment]
> could you make -c for config directory!

Hi @blackcodersec. I was going to close this, but realised I hadn't addressed the initial issue! I was ust wondering why you need have an option `-c` to provide a config directory? Do you need different config files for different things? Is there an issue with the default that other programs use too, e.g. `~/.config/TOOLNAME`?

**Comment by blackcodersec** [comment]
I want to use config file from different directory. That's why I made this issue.

**Comment by xnl-h4ck3r** [comment]
Hi @blackcodersec. The `-c`/`--config` option is now available in latest v2.2. Use `pip install --upgrade urless` to update it.
Let me kno if you have any problems.
Thanks
Xnl

**Comment by blackcodersec** [comment]
thanks for the update.
